<?php

define( 'WANDERLAND_CORE_VERSION', '1.0.1' );
define( 'WANDERLAND_CORE_ABS_PATH', dirname( __FILE__ ) );
define( 'WANDERLAND_CORE_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'WANDERLAND_CORE_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'WANDERLAND_CORE_ASSETS_PATH', WANDERLAND_CORE_ABS_PATH . '/assets' );
define( 'WANDERLAND_CORE_ASSETS_URL_PATH', WANDERLAND_CORE_URL_PATH . 'assets' );
define( 'WANDERLAND_CORE_CPT_PATH', WANDERLAND_CORE_ABS_PATH . '/post-types' );
define( 'WANDERLAND_CORE_CPT_URL_PATH', WANDERLAND_CORE_URL_PATH . 'post-types' );
define( 'WANDERLAND_CORE_SHORTCODES_PATH', WANDERLAND_CORE_ABS_PATH . '/shortcodes' );
define( 'WANDERLAND_CORE_SHORTCODES_URL_PATH', WANDERLAND_CORE_URL_PATH . 'shortcodes' );